version: '3'

services:
  scraper:
    build: .
    restart: unless-stopped
    environment:
      MONGO_URL: "mongodb://mongo:27017"
      SLEEP_TIME: "30"
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4.5
    restart: unless-stopped
    ports:
      - 27018:27017
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

